theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  debug:
    productionUrl: https://lacriee-site.web.deuxfleurs.fr
  menu:
    dropdown:
      linkToLevel1: true
  summary:
    position: content
  plausible: 
  persons:
    index:
      layout: grid
    single:
      backlinks: true
  posts:
    index:
      layout: grid
  breadcrumb:
    position: hero-start
  search:
    active: true
    position: footer
    appearance: both
  organizations:
    single:
      backlinks: true
